// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcjHPJmDgH56XjVp0yIeNuP7DbCRIWXiI',
    appId: '1:24627747502:web:e5b3230a26bbd3b5a22b3f',
    messagingSenderId: '24627747502',
    projectId: 'luxor-meeting',
    authDomain: 'luxor-meeting.firebaseapp.com',
    storageBucket: 'luxor-meeting.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCAfDPqmvNHualiA03mso9cPiKcXi9Aak',
    appId: '1:24627747502:android:58fb14c5373fab17a22b3f',
    messagingSenderId: '24627747502',
    projectId: 'luxor-meeting',
    storageBucket: 'luxor-meeting.firebasestorage.app',
  );

  // TODO: Configure android/ios via FlutterFire CLI

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfouS3jfW9Pj4NvuCWUlt8k6T-35mIjNA',
    appId: '1:24627747502:ios:eb3b11bbf15b7cd3a22b3f',
    messagingSenderId: '24627747502',
    projectId: 'luxor-meeting',
    storageBucket: 'luxor-meeting.firebasestorage.app',
    iosBundleId: 'com.diwizon.luxorDr',
  );

}